### ISSUE TITLE
Backend module tries to load typo3/markjs.js

### ISSUE THREAD

**Issue by oemmes** [fsuter/devlog#1]
Hi François,

many thanks for releasing the new version! It's cool to have the "original" devlog back for Typo3 7.6+.

Though when opening the backend module one of the JavaScript libraries requires "markjs" for which the file `typo3/markjs.js` is tried to load. This fails as the path is obviously not correct.

I installed it using composer in a Typo3 7.6.12 environment.

Just for testing I manually placed the file there and then the backend module works.

Can you confirm and hopefully fix this?

**Comment by fsuter** [comment]
This is really weird. I am indeed using a library called "mark.js" (https://github.com/julmot/mark.js) but there's nowhere where I reference it by the name of "markjs". In `Resources/Public/JavaScript/ListModule.js` it is required with a direct path: `./jquery.mark.min` which is the way to require additional libraries AFAIK (but I'm no RequireJS specialist). The file is located in `devlog/Resources/Public/JavaScript/jquery.mark.min.js` and that works for me.

I don't know if using composer has an impact on this (because I'm not using composer myself), but I would be surprised if it did as we are talking about JS files here and not PHP libraries.

I'm really puzzled and I don't know what to answer. Maybe someone in the community has an idea...

**Comment by oemmes** [comment]
I'm also not very familiar with RequiryJS but I think its origin is within `datatables.mark.min.js`:

````js
define(["jquery","datatables.net","markjs"],function(d){ /* ... */})
````

**Comment by fsuter** [comment]
Hmm, that could be it. I wonder how this can be solved. I'll have to ask around.

Still I wonder why it works for me and not for you...

**Comment by fsuter** [comment]
This is so weird, now I have the problem too 8-O I'll dig in the next few days.

**Comment by oemmes** [comment]
I had a look at this again and think I found a solution by adding "markjs" to the requireJS config map like you already did for datatables.

This works for me:
````js
require.config({
	map: {
		'*': {
			'datatables.net': 'datatables',
			'markjs': 'TYPO3/CMS/Devlog/jquery.mark.min'
		}
	}
});
````

**Comment by fsuter** [comment]
Spot on! I was going to try something like that, after reading the RequireJS documentation over breakfast today, but thanks a lot for digging and coming up with a working solution.
